import { prisma } from "../lib/prisma";

async function main() {
  console.log("Seeding categories...");

  const categoryTree = [
    {
      name: "Academics",
      slug: "academics",
      icon: "BookOpen",
      children: [
        { name: "Mathematics", slug: "mathematics" },
        { name: "Physics", slug: "physics" },
        { name: "Chemistry", slug: "chemistry" },
        { name: "Biology", slug: "biology" },
        { name: "Science", slug: "science" },
        { name: "Environmental Science", slug: "environmental-science" },
        { name: "Commerce & Accounts", slug: "commerce" },
        { name: "Economics", slug: "economics" },
        { name: "Business Studies", slug: "business-studies" },
        { name: "Statistics", slug: "statistics" },
        { name: "Computer Science", slug: "computer-science" },
        { name: "Information Technology", slug: "information-technology" },
        { name: "English", slug: "english" },
        { name: "Hindi", slug: "hindi" },
        { name: "Sanskrit", slug: "sanskrit" },
        { name: "French", slug: "french" },
        { name: "German", slug: "german" },
        { name: "Spanish", slug: "spanish" },
        { name: "Japanese", slug: "japanese" },
        { name: "Chinese (Mandarin)", slug: "mandarin" },
        { name: "History", slug: "history" },
        { name: "Geography", slug: "geography" },
        { name: "Political Science", slug: "political-science" },
        { name: "Civics", slug: "civics" },
        { name: "Sociology", slug: "sociology" },
        { name: "Psychology", slug: "psychology" },
        { name: "Philosophy", slug: "philosophy" },
        { name: "Legal Studies", slug: "legal-studies" },
        { name: "General Knowledge", slug: "general-knowledge" },
        { name: "Reasoning & Aptitude", slug: "reasoning-aptitude" },
        { name: "Entrance Exam Coaching", slug: "entrance-exams" },
        { name: "Competitive Exam Coaching", slug: "competitive-exams" },
      ],
    },

    {
      name: "Sports",
      slug: "sports",
      icon: "Trophy",
      children: [
        { name: "Cricket", slug: "cricket" },
        { name: "Football", slug: "football" },
        { name: "Badminton", slug: "badminton" },
        { name: "Tennis", slug: "tennis" },
        { name: "Table Tennis", slug: "table-tennis" },
        { name: "Swimming", slug: "swimming" },
        { name: "Basketball", slug: "basketball" },
        { name: "Volleyball", slug: "volleyball" },
        { name: "Hockey", slug: "hockey" },
        { name: "Athletics", slug: "athletics" },
        { name: "Gymnastics", slug: "gymnastics" },
        { name: "Chess", slug: "chess" },
        { name: "Skating", slug: "skating" },
        { name: "Cycling", slug: "cycling" },
        { name: "Archery", slug: "archery" },
        { name: "Golf", slug: "golf" },
        { name: "Squash", slug: "squash" },
        { name: "Billiards & Snooker", slug: "billiards-snooker" },
        { name: "Boxing", slug: "boxing" },
        { name: "Wrestling", slug: "wrestling" },
        { name: "Fencing", slug: "fencing" },
        { name: "Shooting", slug: "shooting" },
        { name: "Yoga", slug: "yoga" },
      ],
    },

    {
      name: "Dance",
      slug: "dance",
      icon: "Sparkles",
      children: [
        { name: "Bharatanatyam", slug: "bharatanatyam" },
        { name: "Kathak", slug: "kathak" },
        { name: "Kathakali", slug: "kathakali" },
        { name: "Kuchipudi", slug: "kuchipudi" },
        { name: "Odissi", slug: "odissi" },
        { name: "Manipuri", slug: "manipuri" },
        { name: "Mohiniyattam", slug: "mohiniyattam" },
        { name: "Sattriya", slug: "sattriya" },
        { name: "Hip Hop", slug: "hip-hop" },
        { name: "Contemporary", slug: "contemporary" },
        { name: "Jazz", slug: "jazz" },
        { name: "Ballet", slug: "ballet" },
        { name: "Bollywood", slug: "bollywood" },
        { name: "Freestyle", slug: "freestyle" },
        { name: "Salsa", slug: "salsa" },
        { name: "Bachata", slug: "bachata" },
        { name: "Ballroom", slug: "ballroom" },
        { name: "Latin Dance", slug: "latin-dance" },
        { name: "Tap Dance", slug: "tap-dance" },
        { name: "Folk Dance", slug: "folk-dance" },
        { name: "Bhangra", slug: "bhangra" },
        { name: "Garba & Dandiya", slug: "garba-dandiya" },
        { name: "Zumba", slug: "zumba" },
      ],
    },

    {
      name: "Music",
      slug: "music",
      icon: "Music",
      children: [
        { name: "Vocal Music", slug: "vocal" },
        { name: "Hindustani Classical Vocal", slug: "hindustani-vocal" },
        { name: "Carnatic Vocal", slug: "carnatic-vocal" },
        { name: "Western Vocal", slug: "western-vocal" },
        { name: "Choir Singing", slug: "choir" },
        { name: "Guitar", slug: "guitar" },
        { name: "Bass Guitar", slug: "bass-guitar" },
        { name: "Ukulele", slug: "ukulele" },
        { name: "Piano & Keyboard", slug: "piano" },
        { name: "Violin", slug: "violin" },
        { name: "Cello", slug: "cello" },
        { name: "Flute", slug: "flute" },
        { name: "Saxophone", slug: "saxophone" },
        { name: "Trumpet", slug: "trumpet" },
        { name: "Clarinet", slug: "clarinet" },
        { name: "Drums", slug: "drums" },
        { name: "Tabla", slug: "tabla" },
        { name: "Mridangam", slug: "mridangam" },
        { name: "Dholak", slug: "dholak" },
        { name: "Harmonium", slug: "harmonium" },
        { name: "Sitar", slug: "sitar" },
        { name: "Veena", slug: "veena" },
        { name: "Music Theory", slug: "music-theory" },
        { name: "Music Production", slug: "music-production" },
        { name: "DJ & Mixing", slug: "dj-mixing" },
      ],
    },

    {
      name: "Arts & Crafts",
      slug: "arts",
      icon: "Palette",
      children: [
        { name: "Drawing & Painting", slug: "drawing-painting" },
        { name: "Sketching", slug: "sketching" },
        { name: "Watercolor Painting", slug: "watercolor" },
        { name: "Oil Painting", slug: "oil-painting" },
        { name: "Acrylic Painting", slug: "acrylic-painting" },
        { name: "Digital Art", slug: "digital-art" },
        { name: "Calligraphy", slug: "calligraphy" },
        { name: "Mandala Art", slug: "mandala-art" },
        { name: "Clay Modeling", slug: "clay-modeling" },
        { name: "Sculpture & Pottery", slug: "sculpture" },
        { name: "Photography", slug: "photography" },
        { name: "Videography", slug: "videography" },
        { name: "Graphic Design", slug: "graphic-design" },
        { name: "Animation", slug: "animation" },
        { name: "Fashion Illustration", slug: "fashion-illustration" },
        { name: "Craft & Origami", slug: "craft" },
        { name: "Paper Craft", slug: "paper-craft" },
        { name: "Jewelry Making", slug: "jewelry-making" },
        { name: "Embroidery", slug: "embroidery" },
        { name: "Knitting & Crochet", slug: "knitting-crochet" },
        { name: "DIY Crafts", slug: "diy-crafts" },
      ],
    },

    {
      name: "Coding & Tech",
      slug: "coding",
      icon: "Code",
      children: [
        { name: "Computer Basics", slug: "computer-basics" },
        { name: "Programming Fundamentals", slug: "programming-fundamentals" },
        { name: "Web Development", slug: "web-development" },
        { name: "Frontend Development", slug: "frontend-development" },
        { name: "Backend Development", slug: "backend-development" },
        { name: "Full Stack Development", slug: "full-stack-development" },
        { name: "Python Programming", slug: "python" },
        { name: "Java Programming", slug: "java" },
        { name: "JavaScript", slug: "javascript" },
        { name: "TypeScript", slug: "typescript" },
        { name: "C Programming", slug: "c" },
        { name: "C++ Programming", slug: "cpp" },
        { name: "C#", slug: "csharp" },
        { name: "Go Programming", slug: "go" },
        { name: "Rust Programming", slug: "rust" },
        { name: "PHP", slug: "php" },
        { name: "Swift", slug: "swift" },
        { name: "Kotlin", slug: "kotlin" },
        { name: "Flutter", slug: "flutter" },
        { name: "Android Development", slug: "android-development" },
        { name: "iOS Development", slug: "ios-development" },
        { name: "Game Development", slug: "game-development" },
        { name: "Robotics", slug: "robotics" },
        { name: "Artificial Intelligence", slug: "artificial-intelligence" },
        { name: "Machine Learning", slug: "machine-learning" },
        { name: "Data Science", slug: "data-science" },
        { name: "Cloud Computing", slug: "cloud-computing" },
        { name: "Cybersecurity", slug: "cybersecurity" },
        { name: "Blockchain", slug: "blockchain" },
        { name: "Internet of Things (IoT)", slug: "iot" },
        { name: "UI/UX Design", slug: "ui-ux-design" },
        { name: "Database Management", slug: "database-management" },
        { name: "DevOps", slug: "devops" },
      ],
    },

    {
      name: "Fitness & Wellness",
      slug: "fitness",
      icon: "Heart",
      children: [
        { name: "Personal Training", slug: "personal-training" },
        { name: "Weight Training", slug: "weight-training" },
        { name: "Strength & Conditioning", slug: "strength-conditioning" },
        { name: "Functional Fitness", slug: "functional-fitness" },
        { name: "CrossFit", slug: "crossfit" },
        { name: "Cardio Fitness", slug: "cardio-fitness" },
        { name: "Yoga", slug: "yoga" },
        { name: "Power Yoga", slug: "power-yoga" },
        { name: "Prenatal Yoga", slug: "prenatal-yoga" },
        { name: "Pilates", slug: "pilates" },
        { name: "Aerobics", slug: "aerobics" },
        { name: "Zumba", slug: "zumba" },
        { name: "Meditation", slug: "meditation" },
        { name: "Mindfulness", slug: "mindfulness" },
        { name: "Nutrition & Diet", slug: "nutrition-diet" },
        { name: "Martial Arts & Karate", slug: "martial-arts" },
        { name: "Taekwondo", slug: "taekwondo" },
        { name: "Judo", slug: "judo" },
        { name: "Kung Fu", slug: "kung-fu" },
        { name: "Kickboxing", slug: "kickboxing" },
        { name: "Self Defense", slug: "self-defense" },
      ],
    },
  ];

  for (const cat of categoryTree) {
    const parent = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, icon: cat.icon },
      create: {
        name: cat.name,
        slug: cat.slug,
        icon: cat.icon,
      },
    });

    for (const child of cat.children) {
      await prisma.category.upsert({
        where: { slug: child.slug },
        update: { name: child.name, parentId: parent.id },
        create: {
          name: child.name,
          slug: child.slug,
          parentId: parent.id,
        },
      });
    }
  }

  console.log("Categories seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
